### ISSUE TITLE
Can u check in your snk

### ISSUE THREAD

**Issue by SimonCropp** [mariusz-schimke/GiGraph#200]
to make it easier for people to build

**Comment by mariusz-schimke** [comment]
Hey Simon!

I could do that, but I'm not sure if this is a good practice to publish this file. The snk key identifies me as a publisher of the package on NuGet, and I would prefer it to stay private. I could create a random snk file instead, but I'm sure I will forget about it one day, and publish the package signed with the shared file instead of the original one :).

Another solution I came across is signing assemblies on release builds only, which I've just done. Would that be okay with you? See the [pull request](https://github.com/mariusz-schimke/GiGraph/pull/202).

**Comment by SimonCropp** [comment]
yep the release build change will work for me. but note that the majority of .net projects check in their key. but that is your call
